### ISSUE TITLE
Where can I find the password input field into the storybook? #11667

### ISSUE THREAD

**Issue by cosmin-z** [carbon-design-system/carbon-web-components#1024] opened 2022-06-27 13:40 UTC
I can't find in the storybook, https://web-components.carbondesignsystem.com/?path=/docs/components-input--default,  no reference to a password type field or any kind of attribute for the input field.

Thanks for the help.

**Comment by kennylam** [comment] 2022-09-12 14:15
Duplicate of #1025

**Closed as completed by kennylam** 2022-09-12 14:15 UTC
Labels: status: needs triage 🕵️‍♀️
